AllCops:
  Excludes:
    - vendor/**
    - metadata.rb

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
TrailingWhitespace:
  Enabled: false
NumericLiterals:
  Enabled: false
